# Generated by Django 5.2.8 on 2025-11-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Completed', 'completed'), ('Rejected', 'rejected')], default='Pending', max_length=50)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CupcakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('frosting', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cupcake_orders', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occassion', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('cake_tier', models.PositiveIntegerField()),
                ('base_flavor', models.CharField(max_length=255)),
                ('finish', models.CharField(max_length=255)),
                ('filling', models.CharField(max_length=255)),
                ('coating_color', models.CharField(max_length=255)),
                ('border', models.CharField(default='none', max_length=255)),
                ('border_color', models.CharField(default='none', max_length=255)),
                ('toppings', models.CharField(default='none', max_length=255)),
                ('addons', models.CharField(default='none', max_length=255)),
                ('message_type', models.CharField(default='none', max_length=255)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cake_orders', to='orders.order')),
            ],
        ),
    ]
