# Generated by Django 5.2.8 on 2025-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeorder',
            old_name='finish',
            new_name='occasion',
        ),
        migrations.RemoveField(
            model_name='cakeorder',
            name='occassion',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('claimed', 'Claimed')], default='pending', max_length=50),
        ),
    ]
