# Generated by Django 5.2.8 on 2026-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=50),
        ),
    ]
