# Generated by Django 5.2.8 on 2025-12-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_recipe_recipeingredient_recipe_ingredients'),
        ('orders', '0006_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.recipe'),
        ),
    ]
