# Generated by Django 5.2.8 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ingredients_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
