# Generated by Django 5.2.8 on 2025-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
