# Generated by Django 5.2.8 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipe_is_temporary'),
        ('orders', '0008_order_ingredients_deducted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premade_cakes', to='inventory.recipe'),
        ),
    ]
