# Generated by Django 5.2.8 on 2025-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
