# Generated by Django 5.2.8 on 2025-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
