# Generated by Django 5.2.8 on 2026-04-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_updated_at_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
