# Generated by Django 5.2.8 on 2025-12-09 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 9, 2, 14, 22, 235641, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
