# Generated by Django 5.2.8 on 2026-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
