# Generated by Django 5.2.6 on 2025-09-26 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientstorage',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
