# Generated by Django 5.2.6 on 2025-09-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ingredients_ingredientstorage_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_storage', to='products.ingredient'),
        ),
    ]
