# Generated by Django 5.2.8 on 2026-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(default='dine-in', max_length=10),
        ),
    ]
