# Generated by Django 5.2.8 on 2025-11-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='media/products/'),
        ),
    ]
