# Generated by Django 5.2.8 on 2025-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
