# Generated by Django 5.2.8 on 2025-11-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_transaction_gross_total_transaction_net_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gross_total',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='net_total',
        ),
    ]
