# Generated by Django 5.2.8 on 2026-03-18 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_discount_rate_discount_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 2, 6, 54, 305252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='discounts', to='pos.category'),
        ),
    ]
