# Generated by Django 5.2.8 on 2025-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_transaction_gross_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
