# Generated by Django 5.2.8 on 2025-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_transaction_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine IN'), ('take-out', 'Take OUT')], default='dine-in', max_length=10),
        ),
    ]
