# Generated by Django 5.2.8 on 2026-03-18 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_discount_end_date_discountusage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountproductrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discountproductrule',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountproductrule',
            name='product',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 2, 24, 47, 931446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DiscountApplication',
        ),
        migrations.DeleteModel(
            name='DiscountProductRule',
        ),
    ]
