# Generated by Django 5.2.8 on 2026-03-18 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_discountproductrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='pos.category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 14, 8, 26, 14420, tzinfo=datetime.timezone.utc)),
        ),
    ]
