# Generated by Django 5.2.8 on 2025-11-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_transaction_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
