# Generated by Django 5.2.8 on 2025-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Business', max_length=100)),
                ('address', models.TextField(blank=True, verbose_name='Business Address')),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='Tax Identification Number (TIN)')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message to appear at the bottom of the receipt (e.g. Thank you!)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
