# Generated by Django 5.2.8 on 2026-03-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_transactionitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 10, 21, 36, 253518, tzinfo=datetime.timezone.utc)),
        ),
    ]
