# Generated by Django 5.2.8 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipe_is_temporary'),
        ('pos', '0009_alter_discount_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_products', to='inventory.recipe'),
        ),
    ]
