# Generated by Django 5.2.8 on 2026-03-22 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_product_recipe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 15, 24, 39, 687684, tzinfo=datetime.timezone.utc)),
        ),
    ]
