# Generated by Django 5.2.8 on 2025-12-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_product_image_path_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
