# Generated by Django 5.2.8 on 2025-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
