# Generated by Django 5.2.8 on 2025-12-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_productsize_size_delete_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='price',
        ),
    ]
