# Generated by Django on 2026-03-23

import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_mark_existing_transactions_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(default=django.utils.timezone.localdate)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=11)),
                ('removed_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=11)),
                ('is_closed', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-opened_at'],
                'unique_together': {('cashier', 'business_date')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pos.cashsession'),
        ),
    ]
