# Generated by Django 5.2.8 on 2025-12-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_remove_transactionitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
