# Generated by Django 5.2.8 on 2025-12-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_transaction_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='display_id',
        ),
    ]
