# Generated by Django 5.2.8 on 2026-03-23 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_cashsession_transaction_cash_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 15, 35, 52, 869362, tzinfo=datetime.timezone.utc)),
        ),
    ]
