# Generated by Django 5.2.8 on 2025-12-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_remove_transaction_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='product_size',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pos.product')),
            ],
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.productvariant'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
