# Generated by Django 5.2.5 on 2026-03-24

import django.db.models.deletion
import decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_discount_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_register_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_session',
        ),
        migrations.CreateModel(
            name='RegisterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_money', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=11)),
                ('current_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=11)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='register_money', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cashier__username'],
            },
        ),
        migrations.CreateModel(
            name='RegisterDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_deductions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_register_deductions', to=settings.AUTH_USER_MODEL)),
                ('register_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='pos.registermoney')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CashSession',
        ),
    ]
