# Generated by Django 5.2.5 on 2026-03-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_register_transactions_from_deductions(apps, schema_editor):
    RegisterDeduction = apps.get_model('pos', 'RegisterDeduction')
    RegisterTransaction = apps.get_model('pos', 'RegisterTransaction')

    for deduction in RegisterDeduction.objects.all().iterator():
        RegisterTransaction.objects.create(
            register_money=deduction.register_money,
            cashier=deduction.cashier,
            entry_type='deduction',
            amount=deduction.amount,
            note=deduction.note,
            created_by=deduction.created_by,
            created_at=deduction.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_register_money_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('addition', 'Addition'), ('deduction', 'Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_register_transactions', to=settings.AUTH_USER_MODEL)),
                ('register_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_transactions', to='pos.registermoney')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_register_transactions_from_deductions, migrations.RunPython.noop),
    ]
