# Generated by Django 5.2.5 on 2026-03-24

from django.db import migrations, models
from django.utils import timezone


def backfill_transaction_sequences(apps, schema_editor):
    Transaction = apps.get_model('pos', 'Transaction')
    DailyOrderCounter = apps.get_model('pos', 'DailyOrderCounter')

    per_day_counts = {}

    transactions = Transaction.objects.all().order_by('created_at', 'id')

    for transaction in transactions.iterator():
        created_at = transaction.created_at

        if created_at is None:
            sequence_date = timezone.localdate()
        elif timezone.is_aware(created_at):
            sequence_date = timezone.localtime(created_at).date()
        else:
            sequence_date = created_at.date()

        next_number = per_day_counts.get(sequence_date, 0) + 1
        per_day_counts[sequence_date] = next_number

        Transaction.objects.filter(pk=transaction.pk).update(
            sequence_date=sequence_date,
            sequence_number=next_number,
        )

    DailyOrderCounter.objects.bulk_create(
        [
            DailyOrderCounter(sequence_date=sequence_date, last_number=last_number)
            for sequence_date, last_number in per_day_counts.items()
        ]
    )


def reverse_backfill_transaction_sequences(apps, schema_editor):
    Transaction = apps.get_model('pos', 'Transaction')
    DailyOrderCounter = apps.get_model('pos', 'DailyOrderCounter')

    Transaction.objects.all().update(sequence_date=None, sequence_number=None)
    DailyOrderCounter.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_registertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sequence_date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='sequence_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_transaction_sequences, reverse_backfill_transaction_sequences),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('sequence_date', 'sequence_number'), name='unique_daily_transaction_sequence_number'),
        ),
    ]
