# Generated by Django 5.2.8 on 2026-02-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='logo',
        ),
    ]
