# Generated by Django 5.2.5 on 2026-03-24

from django.db import migrations
from django.db.models import F


def backfill_void_transactions_completed(apps, schema_editor):
    Transaction = apps.get_model('pos', 'Transaction')

    Transaction.objects.filter(
        is_void=True,
        is_completed=False,
    ).update(is_completed=True)

    Transaction.objects.filter(
        is_void=True,
        completed_at__isnull=True,
    ).update(completed_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_daily_order_sequence'),
    ]

    operations = [
        migrations.RunPython(backfill_void_transactions_completed, migrations.RunPython.noop),
    ]
