# Generated by Django 5.2.8 on 2026-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_remove_businesssettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='void_pin',
            field=models.IntegerField(default=1234),
        ),
    ]
