# Generated by Django 5.2.8 on 2026-03-24 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_backfill_void_transactions_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 1, 52, 0, 611150, tzinfo=datetime.timezone.utc)),
        ),
    ]
