# Generated by Django 5.2.8 on 2026-02-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_businesssettings_void_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssettings',
            old_name='void_pin',
            new_name='secret_pin',
        ),
    ]
