# Generated by Django 5.2.8 on 2026-04-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_discount_indefinite_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountusage',
            name='discount_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='pos.discount'),
        ),
    ]
