# Generated by Django 5.2.8 on 2026-04-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_discountusage_discount_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
