# Generated by Django 5.2.8 on 2026-04-02 05:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_transaction_discount_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='secret_pin',
            field=models.CharField(default=1234),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='registerdeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='starting_money',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='registertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
