# Generated by Django 5.2.8 on 2026-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_alter_businesssettings_secret_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='secret_pin',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
