# Generated by Django 5.2.8 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_alter_businesssettings_secret_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='gcash_owner_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='gcash_owner_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
