# Generated by Django 5.2.8 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_businesssettings_gcash_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
