# Generated by Django 5.2.8 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_transaction_payment_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='usage_type',
            field=models.CharField(
                choices=[('per_order', 'Per Order'), ('per_product', 'Per Product')],
                default='per_order',
                max_length=30,
            ),
        ),
    ]
