const API_ENDPOINTS = {
    BUSINESS_DETAILS: "/pos/business-details/",
    CAKES: "/orders/cakes/",
    CAKES_UNARCHIVE: "/orders/cakes/unarchive/",
    USERS: "/users/",
    USERS_REGISTER: "/users/user/register/",
    USERS_ACTIVATE: "/users/user/activate/",
    CATEGORIES: "/pos/categories/",
    DISCOUNTS: "/pos/discounts/",
    DISCOUNT_USAGE: "/pos/discount-usage/",
    INGREDIENTS: "/inventory/ingredients/",
    INGREDIENTS_ALL: "/inventory/ingredients-all/",
    INGREDIENTS_DASHBOARD: "/inventory/dashboard/",
    INGREDIENTS_STOCK_OUT_EXPIRED: "/inventory/ingredients/stock-out-expired/",
    INVENTORY_TRANSACTIONS: "/inventory/transactions/",
    ORDERS: "/orders/orders/",
    ORDERS_DEDUCT_INGREDIENTS: "/orders/orders/{id}/deduct-ingredients/",
    ORDERS_BATCH_UPDATE: "/orders/orders/batch-update/",
    BLOCKED_DATES: "/orders/blocked-dates/",
    OPENING_TIME: "/orders/opening-time/",
    PRODUCTS: "/pos/products/",
    PRODUCTS_ALL: "/pos/products/get_all/",
    PRODUCTS_UNARCHIVE: "/pos/products/unarchive/",
    RECIPES: "/inventory/recipes/",
    SIZES: "/pos/sizes/",
    TRANSACTIONS: "/pos/transactions/",
    TRANSACTIONS_OPEN_DAY: "/pos/transactions/open-day/",
    TRANSACTIONS_DAY_SESSION: "/pos/transactions/day-session/",
    TRANSACTIONS_CLOSE_DAY: "/pos/transactions/close-day/",
    UNITS: "/inventory/units/",
    POS_DASHBOARD: "/pos/dashboard/",
    ORDERS_DASHBOARD: "/orders/dashboard/",
    PAYMENT_HISTORY: "/payment/history/",
};

export default API_ENDPOINTS;