# Generated by Django 5.2.8 on 2025-11-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('remaining_stock', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_stock', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.ingredient')),
            ],
        ),
    ]
