# Generated by Django 5.2.8 on 2025-11-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
