# Generated by Django 5.2.8 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dimension',
            field=models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('count', 'Count')], default='mass', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='multiplier_to_reference',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='total_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_needed',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='IngredientUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier_to_base', models.DecimalField(decimal_places=6, max_digits=14)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_conversion_sources', to='inventory.unit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='inventory.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'from_unit')},
            },
        ),
    ]
