# Generated by Django 5.2.8 on 2025-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_transaction_total_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='remaining_stock',
        ),
        migrations.AddField(
            model_name='transaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
