# Generated by Django 5.2.8 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_flexible_units_and_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
