# Generated by Django 5.2.8 on 2025-11-21 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_ingredient_remaining_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 21, 16, 55, 39, 918777, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
