# Generated by Django 5.2.8 on 2025-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
