# Generated by Django 5.2.8 on 2025-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_transaction_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pc', 'Pieces'), ('st', 'Sticks'), ('ml', 'Milliliter'), ('cp', 'Cup')], max_length=2),
        ),
    ]
