# Generated by Django 5.2.8 on 2025-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_recipe_recipeingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
