# Generated by Django 5.2.8 on 2026-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_transaction_cost_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
