# Generated by Django 5.2.8 on 2026-04-08

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def seed_and_normalize_units(apps, schema_editor):
    Dimension = apps.get_model("inventory", "Dimension")
    Unit = apps.get_model("inventory", "Unit")
    Ingredient = apps.get_model("inventory", "Ingredient")
    Transaction = apps.get_model("inventory", "Transaction")
    RecipeIngredient = apps.get_model("inventory", "RecipeIngredient")
    IngredientUnitConversion = apps.get_model("inventory", "IngredientUnitConversion")
    Inventory = apps.get_model("inventory", "Inventory")

    dimensions = {
        "weight": Dimension.objects.get_or_create(name="weight")[0],
        "volume": Dimension.objects.get_or_create(name="volume")[0],
        "count": Dimension.objects.get_or_create(name="count")[0],
    }

    legacy_to_new_dimension = {
        "mass": "weight",
        "weight": "weight",
        "volume": "volume",
        "count": "count",
    }

    Unit.objects.update(is_base=False)

    for unit in Unit.objects.all():
        legacy_dimension = getattr(unit, "dimension", None)
        mapped_dimension_name = legacy_to_new_dimension.get(legacy_dimension or "", "count")
        unit.dimension_ref = dimensions[mapped_dimension_name]

        legacy_factor = getattr(unit, "multiplier_to_reference", None)
        unit.to_base_factor = Decimal(str(legacy_factor or "1"))
        unit.save(update_fields=["dimension_ref", "to_base_factor", "is_base"])

    seed_units = [
        ("mg", "Milligram", "weight", Decimal("0.001"), False),
        ("g", "Gram", "weight", Decimal("1"), True),
        ("kg", "Kilogram", "weight", Decimal("1000"), False),
        ("oz", "Ounce", "weight", Decimal("28.3495"), False),
        ("lb", "Pound", "weight", Decimal("453.592"), False),
        ("ml", "Milliliter", "volume", Decimal("1"), True),
        ("L", "Liter", "volume", Decimal("1000"), False),
        ("tsp", "Teaspoon", "volume", Decimal("5"), False),
        ("tbsp", "Tablespoon", "volume", Decimal("15"), False),
        ("cup", "Cup", "volume", Decimal("240"), False),
        ("pcs", "Piece", "count", Decimal("1"), True),
        ("dozen", "Dozen", "count", Decimal("12"), False),
    ]

    base_units_by_dimension_id = {}

    for symbol, name, dimension_name, factor, is_base in seed_units:
        dimension_ref = dimensions[dimension_name]

        unit = Unit.objects.filter(symbol__iexact=symbol).first()
        if unit is None:
            unit = Unit.objects.filter(name__iexact=name).first()

        if unit is None:
            unit = Unit.objects.create(
                name=name,
                symbol=symbol,
                dimension_ref=dimension_ref,
                to_base_factor=factor,
                is_base=is_base,
            )
        else:
            unit.name = name
            unit.symbol = symbol
            unit.dimension_ref = dimension_ref
            unit.to_base_factor = factor
            unit.is_base = is_base
            unit.save(update_fields=["name", "symbol", "dimension_ref", "to_base_factor", "is_base"])

        if is_base:
            base_units_by_dimension_id[dimension_ref.id] = unit

    for ingredient in Ingredient.objects.select_related("unit").all():
        current_unit = ingredient.unit
        dimension_id = getattr(current_unit, "dimension_ref_id", None)
        if not dimension_id:
            dimension_id = dimensions["count"].id

        target_base_unit = base_units_by_dimension_id.get(dimension_id)
        if target_base_unit is None:
            continue

        from_factor = Decimal(str(getattr(current_unit, "to_base_factor", Decimal("1")) or Decimal("1")))
        base_factor = Decimal(str(getattr(target_base_unit, "to_base_factor", Decimal("1")) or Decimal("1")))
        if base_factor == 0:
            base_factor = Decimal("1")

        multiplier_to_base = from_factor / base_factor

        ingredient.total_stock = Decimal(str(ingredient.total_stock or "0")) * multiplier_to_base
        ingredient.low_amount = Decimal(str(ingredient.low_amount or "0")) * multiplier_to_base
        ingredient.unit = target_base_unit
        ingredient.save(update_fields=["total_stock", "low_amount", "unit"])

        for tx in Transaction.objects.filter(ingredient_id=ingredient.id):
            tx.amount = Decimal(str(tx.amount or "0")) * multiplier_to_base
            tx.remaining_amount = Decimal(str(tx.remaining_amount or "0")) * multiplier_to_base
            tx.save(update_fields=["amount", "remaining_amount"])

        for recipe_ingredient in RecipeIngredient.objects.filter(ingredient_id=ingredient.id):
            recipe_ingredient.amount_needed = Decimal(str(recipe_ingredient.amount_needed or "0")) * multiplier_to_base
            recipe_ingredient.save(update_fields=["amount_needed"])

        for conversion in IngredientUnitConversion.objects.filter(ingredient_id=ingredient.id):
            legacy_multiplier = Decimal(str(getattr(conversion, "multiplier_to_base", Decimal("1")) or Decimal("1")))
            conversion.factor = legacy_multiplier * multiplier_to_base
            conversion.to_unit = target_base_unit
            conversion.save(update_fields=["factor", "to_unit"])

        Inventory.objects.update_or_create(
            item_id=ingredient.id,
            defaults={"quantity_base": ingredient.total_stock},
        )

    for conversion in IngredientUnitConversion.objects.filter(to_unit__isnull=True):
        conversion.to_unit_id = conversion.ingredient.unit_id
        conversion.factor = conversion.factor or Decimal("1")
        conversion.save(update_fields=["to_unit", "factor"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_unit_abbreviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_base", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="inventory.ingredient"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.ingredient",),
        ),
        migrations.CreateModel(
            name="ItemUnitConversion",
            fields=[],
            options={
                "verbose_name": "Item Unit Conversion",
                "verbose_name_plural": "Item Unit Conversions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.ingredientunitconversion",),
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="abbreviation",
            new_name="symbol",
        ),
        migrations.AddField(
            model_name="unit",
            name="dimension_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="legacy_units", to="inventory.dimension"),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_base",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="to_base_factor",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AlterUniqueTogether(
            name="ingredientunitconversion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ingredientunitconversion",
            name="factor",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="ingredientunitconversion",
            name="to_unit",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ingredient_conversion_targets", to="inventory.unit"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="low_amount",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="total_stock",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_needed",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.RunPython(seed_and_normalize_units, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="unit",
            name="dimension",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="dimension_ref",
            new_name="dimension",
        ),
        migrations.AlterField(
            model_name="unit",
            name="dimension",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="units", to="inventory.dimension"),
        ),
        migrations.RemoveField(
            model_name="unit",
            name="multiplier_to_reference",
        ),
        migrations.RemoveField(
            model_name="ingredientunitconversion",
            name="multiplier_to_base",
        ),
        migrations.AlterField(
            model_name="ingredientunitconversion",
            name="factor",
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name="ingredientunitconversion",
            name="to_unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ingredient_conversion_targets", to="inventory.unit"),
        ),
        migrations.AddIndex(
            model_name="ingredientunitconversion",
            index=models.Index(fields=["ingredient", "from_unit", "to_unit"], name="inventory_i_ingredi_d434b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="ingredientunitconversion",
            constraint=models.UniqueConstraint(fields=("ingredient", "from_unit", "to_unit"), name="unique_item_unit_conversion_pair"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["dimension", "to_base_factor"], name="inventory_u_dimensi_c2273a_idx"),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(condition=models.Q(("is_base", True)), fields=("dimension",), name="unique_base_unit_per_dimension"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["updated_at"], name="inventory_i_updated_22da79_idx"),
        ),
    ]
