# Generated by Django 5.2.8 on 2026-02-17 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_ingredient_soft_unit_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='soft_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.unit'),
        ),
    ]
