# Generated by Django 5.2.8 on 2026-02-08 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 8, 12, 45, 26, 833636, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
