# Generated by Django 5.2.8 on 2026-04-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
