# Generated by Django 5.2.8 on 2026-04-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
